### ISSUE TITLE
it's not working

### ISSUE THREAD

**Issue by vittbol** [VrtK/Heartwood-bot#1]
He found the ore, but then he lost it and keep going down
![image](https://github.com/VrtK/Heartwood-bot/assets/8014813/e6550986-1b5c-4476-8d6a-f6e167d179e7)

**Comment by VrtK** [comment]
Is seems the bot didn't detect the main area for mining, where are you trying use the bot?

**Comment by vittbol** [comment]
Exactly the area from your print

**Comment by VrtK** [comment]
take a new image of some static object next to your mining area and please update, the main static object can be found here- /MISC/mining/main.JPG

BTW, make sure you run under 1600X900 resolution

**Comment by vittbol** [comment]
![image](https://github.com/VrtK/Heartwood-bot/assets/8014813/473ad27e-57e0-47ca-93e5-64ebaf121ca8)
![image](https://github.com/VrtK/Heartwood-bot/assets/8014813/fdbcafd6-963d-4e10-8015-95104fb0ca2a)
![image](https://github.com/VrtK/Heartwood-bot/assets/8014813/b2ce11d0-f9a0-4d80-8717-fb3b1d324745)
All settings are fine.
Saved a new static object.
![image](https://github.com/VrtK/Heartwood-bot/assets/8014813/c94c6506-a1fb-4a60-b317-95c4fea1fb00)
Found the ore.
![image](https://github.com/VrtK/Heartwood-bot/assets/8014813/c33fcfe3-cc59-41e2-b845-7c8235f6125e)
Still going down
![image](https://github.com/VrtK/Heartwood-bot/assets/8014813/66a402de-59c2-4f4f-9465-9e1fda5fb202)

**Comment by VrtK** [comment]
maybe you getting different numbers, please replace line 262 with this code
print(f'Cannot find main obj, lets search it, val:{max_val}')
and write me the score you getting

**Comment by Notananonname** [comment]
It worked for me but I had to edit both main.JPG and Capture.JPG. I took a screenshot and edited it. Thank you for this!

**Comment by VrtK** [comment]
Happy it worked for you!
